path: "/data/Marine_picture/"
train: 
    - Video/images/train
    - Marine_yolo_10m_only/images/train
    - Marine_yolo_25m_only/images/train
    - Marine_yolo_35m_only/images/train
    - Video/images/test
val:
    - Marine_yolo_10m_only/images/test
    - Marine_yolo_25m_only/images/test
    - Marine_yolo_35m_only/images/test
    
# Classes
names:
  0: living creature
  
