path: "/data/Marine_picture/"
train: 
    - Marine_yolo_35m_only/images/train
val:
    - Marine_yolo_35m_only/images/test
    
# Classes
names:
  0: chaetognath
  1: larval fish
  2: Hydromedusa
  3: lobate ctenophore
  4: Pleurobrachia
  5: shrimp 
  6: Siphonophore
  7: stomatopod larva
  8: Unknown
  9: Thaliac
  10: Polychaete
  11: Cumacean
  12: Ctenophore
  
