path: "/data/Marine_picture/"
train: 
    - Marine_yolo_10m_only/images/train
    - Marine_yolo_25m_only/images/train
    - Marine_yolo_35m_only/images/train
val:
    - Marine_yolo_10m_only/images/val
    - Marine_yolo_25m_only/images/val
    - Marine_yolo_35m_only/images/val
    
# Classes
names:
  0: living creature

