path: "/data/Marine_picture/"
train: 
    - Marine_yolo_25m_data/images
val:
    - Marine_yolo_35m_data/images
    
# Classes
names:
  0: chaetognath
  1: larval fish
  2: Hydromedusa
  3: lobate ctenophore
  4: Pleurobrachia
  5: shrimp 
  6: Siphonophore
  7: stomatopod larva
  8: Unknown
  9: Thaliac
  10: Poly
  11: Cumacean
  12: Cteno
  
